name: kafka

on:
  pull_request


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - run: npm install && docker-compose -up d
      - run: node consumer.js && node anotherconsumer.js
      - run: node producer.js